### ISSUE TITLE
感恩作者！

### ISSUE THREAD

**Issue by doveppp** [WindrunnerMax/SW#25]
虽然不知道发生了什么  感谢作者的产品

**Comment by freemedom** [comment]
app.do接口出问题了

**Comment by freemedom** [comment]
<html>
	<head>
	<base target="_self"/>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>出错页面</title>
		<style type="text/css">
		
		</style> 
		<script language='javascript'>
			var flag='1';
			if(flag=='1' || flag=='2' ){ 
				window.location.href="/Logon.do?method=logout";
			}
		</script>
	</head> 
	<body>
		<div align="center">
			<table width="50%" border="0">
				<tr>
					<td>
						<div align="center">
							<img src="/framework/images/chucuole.gif" width="105" height="110">
						</div>
					</td>
				</tr>
				<tr>
					<td height="50px">
						<div align="center">
							<font color="blue">用户没有登录，请重新登录！</font>
						</div>
					</td>
				</tr>
			</table>
		</div>
	</body> 
</html>

**Comment by freemedom** [comment]
看了下强智似乎不返回json，这样就只能解析table了
登录加密也是个问题

**Comment by WindRunnerMax** [comment]
山科小站plus正在酝酿中

**Comment by WindRunnerMax** [comment]
这个问题学校也就背两成的锅，大锅在强智那边，学校升级了系统，强智把接口在这次升级给ban了

**Comment by WindRunnerMax** [comment]
山科小站已恢复，山科小站plus也继续服役
