### ISSUE TITLE
小站ultra 查教室bug

### ISSUE THREAD

**Issue by Sh4peshifting** [WindrunnerMax/SW#28]
小站ultra 查询34 78 9X节课的空教室存在卡加载的情况，查询其他节课的空教室均正常
![Screenshot_20240422-213654](https://github.com/WindrunnerMax/SHST/assets/56795584/59b264e5-02fb-447e-8482-1e40f5fbbd27)

**Comment by WindRunnerMax** [comment]
https://github.com/SHST-SDUST/SHST-ULTRA/commit/ffa2b4b27853bdbfbf2b146a5166454f91eb2daf

下次发版会修复
