### ISSUE TITLE
是否有一个API可以一次性获得一学期的课程

### ISSUE THREAD

**Issue by WindGiang** [WindrunnerMax/SW#5]
如标题，我尝试了method为 getKbcx时返回的错误代码为500，但我应该遗漏了其他的参数，请问作者是否了解

**Comment by WindrunnerMax** [comment]
如果除了登录接口，其它接口的调用全部为500的话，说明你学校未开放接口

**Comment by WindrunnerMax** [comment]
此外没有取得全部课程的接口，只能从网页版解析HTML获取

**Comment by WindGiang** [comment]
感谢，调用单周的课表可以，我就用了一个很笨的方法，给学期课表合并了
`    def getKbcx(self, week=20):
        list_class = []
        s = json.loads(self.getCurrentTime())
        for i in range(1, week+1):
            params = {
                "method": "getKbcxAzc",
                "xnxqid": s['xnxqh'],
                "zc": i,
                "xh": self.account
            }
            req = self.GetHandle(params)
            c = eval(req.text)
            for class_l in c:
                if class_l not in list_class:
                    print(class_l)
                    list_class.append(class_l)
        return list_class`
虽然比较费时，但只能凑合用了。

**Comment by WindrunnerMax** [comment]
你这真猛，注意一下强智数据请求过快会封禁ip一小时
